<?xml version="1.0"?>
<!DOCTYPE sources [
        <!ELEMENT sources (source+)>
        <!ELEMENT source (name,children+)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT children (node*)>
        <!ELEMENT node (name,function,inputs,children+)>
        <!ELEMENT inputs (input+)>
        <!ELEMENT input (name,type)>
        <!ELEMENT type (#PCDATA)>
        <!ELEMENT function (#PCDATA)>
        ]>
<sources>
    <source>
        <name>Facebook</name>
        <children>
            <node>
                <name>Page</name>
                <function>page</function>
                <inputs>
                    <input>
                        <name>Page id</name>
                        <type>text</type>
                    </input>
                </inputs>
                <children>
                    <node>
                        <name>Feed</name>
                        <function>page_feed</function>
                        <inputs>
                            <input>
                                <name>Page id</name>
                                <type>text</type>
                            </input>
                        </inputs>
                        <children>
                            <node>
                                <name>Comments</name>
                                <function>page_feed_comments</function>
                                <inputs>
                                    <input>
                                        <name>Page id</name>
                                        <type>text</type>
                                    </input>
                                </inputs>
                                <children></children>
                            </node>
                        </children>
                    </node>
                </children>
            </node>
            <node>
                <name>Post</name>
                <function>post</function>
                <inputs>
                    <input>
                        <name>Post id</name>
                        <type>text</type>
                    </input>
                </inputs>
                <children></children>
            </node>
        </children>
    </source>
    <source>
        <name>Twitter</name>
        <children></children>
    </source>
    <source>
        <name>Reddit</name>
        <children></children>
    </source>
    <source>
        <name>YouTube</name>
        <children></children>
    </source>
    <source>
        <name>Tumblr</name>
        <children></children>
    </source>
    <source>
        <name>Instagram</name>
        <children></children>
    </source>
    <source>
        <name>HackerNews</name>
        <children></children>
    </source>
    <source>
        <name>LinkedIn</name>
        <children></children>
    </source>
    <source>
        <name>Meetup</name>
        <children></children>
    </source>
    <source>
        <name>Eventbrite</name>
        <children></children>
    </source>
    <source>
        <name>Pintrest</name>
        <children></children>
    </source>
    <source>
        <name>VK</name>
        <children></children>
    </source>
    <source>
        <name>Imgur</name>
        <children></children>
    </source>
    <source>
        <name>Twitch</name>
        <children></children>
    </source>
    <source>
        <name>DeviantArt</name>
        <children></children>
    </source>
</sources>
