=== 5l1v3r1/reaper-3/sources/source.dtd
<?xml version="1.0"?>
<!ELEMENT source (name,keys,children+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT keys (key*)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT children (node*)>
<!ELEMENT node (name,function,inputs,children+)>
<!ELEMENT inputs (input+)>
<!ELEMENT input (name,type,elems*,columns*,rows*,setters*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT elems (elem*)>
<!ELEMENT elem (#PCDATA)>
<!ELEMENT rows (row*)>
<!ELEMENT row (cell*)>
<!ELEMENT cell (#PCDATA)>
<!ELEMENT columns (column*)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT setters (setter*)>
<!ELEMENT setter (name,argument,value,type)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT function (#PCDATA)>
<!ATTLIST input required CDATA #IMPLIED>

=== 5l1v3r1/reaper-3/sources/reddit.xml
<?xml version="1.0"?>
<!DOCTYPE source SYSTEM "source.dtd">
<source>
        <name>Reddit</name>
        <keys>
            <key>application_id</key>
            <key>application_secret</key>
        </keys>
        <children>
            <node>
                <name>Search</name>
                <function>search</function>
                <inputs>
                    <input>
                        <name required="true">query</name>
                        <type>primary</type>
                    </input>
                    <input>
                        <name>Arguments</name>
                        <type>arguments</type>
                        <columns>
                            <column>Argument</column>
                            <column>Value</column>
                        </columns>
                        <setters>
                            <setter>
                                <name>Order</name>
                                <argument>order</argument>
                                <value>top,new,relevance,comments</value>
                                <type>list</type>
                            </setter>
                            <setter>
                                <name>Count</name>
                                <argument>count</argument>
                                <value>1000</value>
                                <type>counter</type>
                            </setter>
                            <setter>
                                <name>Time period</name>
                                <argument>time_period</argument>
                                <value>all,year,month,week,today,hour</value>
                                <type>list</type>
                            </setter>
                        </setters>
                    </input>
                </inputs>
                <children/>
            </node>
            <node>
                <name>Subreddit</name>
                <function>subreddit</function>
                <inputs>
                    <input>
                        <name required="true">subreddit</name>
                        <type>primary</type>
                    </input>
                    <input>
                        <name>Arguments</name>
                        <type>arguments</type>
                        <columns>
                            <column>Argument</column>
                            <column>Value</column>
                        </columns>
                        <setters>
                            <setter>
                                <name>Category</name>
                                <argument>category</argument>
                                <value>top,new,hot,rising,controversial</value>
                                <type>list</type>
                            </setter>
                            <setter>
                                <name>Count</name>
                                <argument>count</argument>
                                <value>1000</value>
                                <type>counter</type>
                            </setter>
                            <setter>
                                <name>Time period</name>
                                <argument>time_period</argument>
                                <value>all,year,month,week,today,hour</value>
                                <type>list</type>
                            </setter>
                        </setters>
                    </input>
                </inputs>
                <children/>
            </node>
            <node>
                <name>User</name>
                <function>user</function>
                <inputs>
                    <input>
                        <name required="true">user</name>
                        <type>primary</type>
                    </input>
                    <input>
                        <name>Arguments</name>
                        <type>arguments</type>
                        <columns>
                            <column>Argument</column>
                            <column>Value</column>
                        </columns>
                        <setters>
                            <setter>
                                <name>Result type</name>
                                <argument>result_type</argument>
                                <value>overview,submitted,comments,guilded</value>
                                <type>list</type>
                            </setter>
                            <setter>
                                <name>Count</name>
                                <argument>count</argument>
                                <value>1000</value>
                                <type>counter</type>
                            </setter>
                            <setter>
                                <name>Order</name>
                                <argument>time_period</argument>
                                <value>new,hot,top,controversial</value>
                                <type>list</type>
                            </setter>
                        </setters>
                    </input>
                </inputs>
                <children/>
            </node>
        </children>
</source>

=== 5l1v3r1/reaper-3/sources/youtube.xml
<?xml version="1.0"?>
<!DOCTYPE source SYSTEM "source.dtd">
<source>
    <name>YouTube</name>
    <keys>
        <key>api_key</key>
    </keys>
    <children>
        <node>
            <name>Search</name>
            <function>search</function>
            <inputs>
                <input required="true">
                    <name>Query</name>
                    <type>primary</type>
                </input>
                <input>
                    <name>Arguments</name>
                    <type>arguments</type>
                    <columns>
                        <column>Argument</column>
                        <column>Value</column>
                    </columns>
                    <setters>
                        <setter>
                            <name>Count</name>
                            <argument>count</argument>
                            <value>1000</value>
                            <type>counter</type>
                        </setter>
                        <setter>
                            <name>Order</name>
                            <argument>order</argument>
                            <value>date,rating,relevance,viewCount,title</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Event type</name>
                            <argument>event_type</argument>
                            <value>completed,live,upcoming</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Safe search</name>
                            <argument>safe_search</argument>
                            <value>moderate,none,strict</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Video caption</name>
                            <argument>video_caption</argument>
                            <value>any,closedCaption,none</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Video definition</name>
                            <argument>video_definition</argument>
                            <value>any,high,standard</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Video dimension</name>
                            <argument>video_dimension</argument>
                            <value>any,2d,3d</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Video duration</name>
                            <argument>video_duration</argument>
                            <value>any,long,medium,short</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Video license</name>
                            <argument>video_license</argument>
                            <value>any,creativeCommon,youtube</value>
                            <type>list</type>
                        </setter>
                        <setter>
                            <name>Video type</name>
                            <argument>video_type</argument>
                            <value>any,episode,movie</value>
                            <type>list</type>
                        </setter>
                    </setters>
                </input>
            </inputs>
            <children/>
        </node>
    </children>
</source>
